# frozen_string_literal: true

require_relative './simple/small_step/reducible'
require_relative './simple/syntax/node'
require_relative './simple/syntax/value'
require_relative './simple/syntax/binary_operator'
require_relative './simple/small_step/binary_operator'
require_relative './simple/syntax/variable'
require_relative './simple/syntax/values'
require_relative './simple/syntax/operators'
require_relative './simple/syntax/assign'
require_relative './simple/syntax/if'
require_relative './simple/syntax/sequence'
require_relative './simple/syntax/while'
require_relative './simple/small_step/do_nothing'
require_relative './simple/small_step/variable'
require_relative './simple/small_step/assign'
require_relative './simple/small_step/if'
require_relative './simple/small_step/sequence'
require_relative './simple/small_step/while'
require_relative './simple/small_step/machine'
